### PR TITLE
Various bug fixes

### PR DESCRIPTION
**Pull request by CS76**
- Firefox, IE scroll fix
- 'free and open-source' anchor link scroll to license fix

### CODE REVIEW

**Comment by johnmay** [comment]
Still not working in Firefox? I click the download button at the top and it doesn't scroll.

**Comment by CS76** [comment]
I don't know the reason but I still see the old js code here h
ttps://github.com/cdk/cdk.github.io/blob/master/js/bundle.443265145c54e94f1b46.js

My local version seems to be fine. Can you build the source locally and run a server to check if it's working?

**Comment by johnmay** [comment]
Hmm, it's got my changes in the HTML. 2 secs

**Comment by johnmay** [comment]
Thanks all good now must have had my local dist left over.

**Comment by CS76** [comment]
There is a typo in the "Get started with CDK" section ( unnecessary - "n" )
screen shot 2017-06-26 at 12 43 52

**Pull request merged**
